# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_multiplication_cpp <- function(A, B) {
    .Call(`_CALDER_matrix_multiplication_cpp`, A, B)
}

matrix_multiplication_sym_cpp <- function(A) {
    .Call(`_CALDER_matrix_multiplication_sym_cpp`, A)
}

loglik_lnorm_cpp <- function(sum_ln1, sum_ln2, p, q) {
    .Call(`_CALDER_loglik_lnorm_cpp`, sum_ln1, sum_ln2, p, q)
}

loglik_lnorm_cpp_vec <- function(vec_values) {
    .Call(`_CALDER_loglik_lnorm_cpp_vec`, vec_values)
}

get_A_len <- function(A) {
    .Call(`_CALDER_get_A_len`, A)
}

get_A_ln1 <- function(A) {
    .Call(`_CALDER_get_A_ln1`, A)
}

get_A_ln2 <- function(A) {
    .Call(`_CALDER_get_A_ln2`, A)
}

loglik_lnorm_cpp_mat <- function(sum_ln1, sum_ln2, ps, qs) {
    .Call(`_CALDER_loglik_lnorm_cpp_mat`, sum_ln1, sum_ln2, ps, qs)
}

zigzag_loglik_ancestors_v4_5 <- function(A, k, min_n_bins = 2L) {
    .Call(`_CALDER_zigzag_loglik_ancestors_v4_5`, A, k, min_n_bins)
}

compute_L <- function(A, L, k) {
    .Call(`_CALDER_compute_L`, A, L, k)
}

